steps:
  - id: 'Install dependencies'
    name: node:18
    entrypoint: npm
    args: ['install']

  - id: 'Lint'
    name: node:18
    entrypoint: npm
    args: ['run', 'lint']

  - id: 'Check typescript'
    name: node:18
    entrypoint: npm
    args: ['run', 'lint:tsc']

  - id: 'Install functions dependencies'
    name: node:18
    dir: 'functions'
    entrypoint: npm
    args: ['install']

  - id: 'Deploy firebase functions'
    name: gcr.io/inothy-firebase/firebase
    args: ['deploy', '--project=inothy-firebase', '--only=functions']
